version: '3'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
#    volumes:   REMOVE COMMENTS IF YOU NEED PERSISTENT DATA.
#      - ./postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres